# Generated by Django 2.1.3 on 2018-12-12 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Radar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('qing', models.IntegerField()),
                ('mai', models.IntegerField()),
                ('wu', models.IntegerField()),
                ('xue', models.IntegerField()),
                ('yu', models.IntegerField()),
                ('yin', models.IntegerField()),
            ],
        ),
    ]
