# Generated by Django 2.1.7 on 2019-03-11 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Diseindicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('nephritis', models.FloatField()),
                ('cystitis', models.FloatField()),
                ('urolithiasis', models.FloatField()),
                ('diabetes', models.FloatField()),
                ('kidneystones', models.FloatField()),
                ('nuclearja', models.FloatField()),
                ('pregnancyhy', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Disewheather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('qing', models.FloatField()),
                ('mai', models.FloatField()),
                ('wu', models.FloatField()),
                ('xue', models.FloatField()),
                ('yu', models.FloatField()),
                ('yin', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=32)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(choices=[('customer', '个人用户'), ('doctor', '专科医生'), ('expert', '疾控专家')], default='customer', max_length=128)),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'ordering': ['-c_time'],
            },
        ),
    ]
