# Generated by Django 2.1.7 on 2019-03-23 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myechartsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(default='北京', max_length=128),
        ),
    ]
