# Generated by Django 2.1.3 on 2018-12-18 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myechartsite', '0002_auto_20181212_2046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zhexiancheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cus_id', models.IntegerField()),
                ('ph', models.FloatField()),
                ('jigan', models.FloatField()),
                ('niaobizhong', models.FloatField()),
                ('niaodanyuan', models.FloatField()),
                ('weidanbai', models.FloatField()),
            ],
        ),
    ]
