# Generated by Django 2.1.7 on 2019-03-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myechartsite', '0002_user_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='disewheather',
            name='year',
            field=models.IntegerField(default=2019),
        ),
    ]
