# Generated by Django 2.1.3 on 2018-12-24 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myechartsite', '0003_zhexiancheck'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Zhexiancheck',
        ),
    ]
