# Generated by Django 2.1.7 on 2019-03-25 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myechartsite', '0003_disewheather_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diseage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('year', models.DateField()),
                ('age0_1', models.IntegerField()),
                ('age1_10', models.IntegerField()),
                ('age11_20', models.IntegerField()),
                ('age21_30', models.IntegerField()),
                ('age31_40', models.IntegerField()),
                ('age41_50', models.IntegerField()),
                ('age51_60', models.IntegerField()),
                ('age61_70', models.IntegerField()),
            ],
        ),
    ]
