# Generated by Django 2.1.7 on 2019-03-27 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myechartsite', '0005_auto_20190325_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disegenderage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('year', models.IntegerField()),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], max_length=32)),
                ('age0_1', models.IntegerField()),
                ('age1_10', models.IntegerField()),
                ('age10_20', models.IntegerField()),
                ('age20_30', models.IntegerField()),
                ('age30_40', models.IntegerField()),
                ('age40_50', models.IntegerField()),
                ('age50_60', models.IntegerField()),
                ('age60_70', models.IntegerField()),
                ('age70_80', models.IntegerField()),
                ('age80_90', models.IntegerField()),
            ],
        ),
    ]
