# Generated by Django 2.1.3 on 2019-01-15 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myechartsite', '0007_auto_20181227_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.CharField(choices=[('customer', '个人用户'), ('doctor', '专科医生'), ('expert', '疾控专家')], default='customer', max_length=128),
        ),
    ]
