# Generated by Django 2.1.7 on 2019-04-09 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myechartsite', '0007_userindicator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diseindicator',
            old_name='cystitis',
            new_name='hhd',
        ),
        migrations.RenameField(
            model_name='diseindicator',
            old_name='diabetes',
            new_name='nsz',
        ),
        migrations.RenameField(
            model_name='diseindicator',
            old_name='kidneystones',
            new_name='pgy',
        ),
        migrations.RenameField(
            model_name='diseindicator',
            old_name='nephritis',
            new_name='rsgxy',
        ),
        migrations.RenameField(
            model_name='diseindicator',
            old_name='nuclearja',
            new_name='sjs',
        ),
        migrations.RenameField(
            model_name='diseindicator',
            old_name='urolithiasis',
            new_name='sy',
        ),
        migrations.RenameField(
            model_name='diseindicator',
            old_name='pregnancyhy',
            new_name='tnb',
        ),
    ]
