# Generated by Django 2.1.7 on 2019-04-11 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myechartsite', '0008_auto_20190409_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inditrend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('indi2008', models.FloatField()),
                ('indi2009', models.FloatField()),
                ('indi2010', models.FloatField()),
                ('indi2011', models.FloatField()),
                ('indi2012', models.FloatField()),
                ('indi2013', models.FloatField()),
                ('indi2014', models.FloatField()),
                ('indi2015', models.FloatField()),
                ('indi2016', models.FloatField()),
                ('indi2017', models.FloatField()),
                ('indi2018', models.FloatField()),
                ('indi2019', models.FloatField()),
            ],
        ),
    ]
