# Generated by Django 2.1.7 on 2019-04-11 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myechartsite', '0009_inditrend'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diseyear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('dise2008', models.FloatField()),
                ('dise2009', models.FloatField()),
                ('dise2010', models.FloatField()),
                ('dise2011', models.FloatField()),
                ('dise2012', models.FloatField()),
                ('dise2013', models.FloatField()),
                ('dise2014', models.FloatField()),
                ('dise2015', models.FloatField()),
                ('dise2016', models.FloatField()),
                ('indi2017', models.FloatField()),
                ('indi2018', models.FloatField()),
                ('dise2019', models.FloatField()),
            ],
        ),
    ]
