# Generated by Django 2.1.7 on 2019-04-11 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myechartsite', '0010_diseyear'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diseyear',
            old_name='indi2017',
            new_name='dise2017',
        ),
        migrations.RenameField(
            model_name='diseyear',
            old_name='indi2018',
            new_name='dise2018',
        ),
    ]
