# Generated by Django 2.1.7 on 2019-04-12 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myechartsite', '0012_disetemp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disemonth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('year', models.IntegerField()),
                ('month1', models.FloatField()),
                ('month2', models.FloatField()),
                ('month3', models.FloatField()),
                ('month4', models.FloatField()),
                ('month5', models.FloatField()),
                ('month6', models.FloatField()),
                ('month7', models.FloatField()),
                ('month8', models.FloatField()),
                ('month9', models.FloatField()),
                ('month10', models.FloatField()),
                ('month11', models.FloatField()),
                ('month12', models.FloatField()),
            ],
        ),
    ]
