# Generated by Django 2.1.7 on 2019-04-17 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myechartsite', '0013_disemonth'),
    ]

    operations = [
        migrations.CreateModel(
                            name='Wheather',
                            fields=[
                                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                                ('location', models.CharField(max_length=256)),
                                ('tempnow', models.IntegerField()),
                                ('tempmin', models.IntegerField()),
                                ('tempmax', models.IntegerField()),
                                ('aqi', models.IntegerField()),
                                ('aqic', models.CharField(max_length=128)),
                                ('wheather', models.CharField(max_length=256)),
                            ],
                        ),
    ]
