# Generated by Django 2.1.7 on 2019-04-21 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myechartsite', '0014_wheather'),
    ]

    operations = [

    ]
