# Generated by Django 2.1.7 on 2019-04-21 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myechartsite', '0014_wheather'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('introduction', models.CharField(max_length=512)),
                ('content', models.TextField()),
                ('imgurl', models.URLField()),
            ],
        ),
    ]
