# Generated by Django 2.1.7 on 2019-04-21 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myechartsite', '0015_delete_article'),
        ('myechartsite', '0017_article'),
    ]

    operations = [
    ]
