# Generated by Django 2.1.7 on 2019-04-22 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myechartsite', '0018_merge_20190421_1635'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
