# Generated by Django 2.1.7 on 2019-04-24 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myechartsite', '0021_diseaqi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userindicator',
            name='name',
        ),
        migrations.AddField(
            model_name='userindicator',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='myechartsite.User'),
            preserve_default=False,
        ),
    ]
