# Generated by Django 2.1.7 on 2019-05-08 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myechartsite', '0027_article_aid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='aid',
            field=models.IntegerField(default=111),
        ),
    ]
